  --  "neovim/nvim-lspconfig",
  --{
  --},
  --{
  --  "mason-org/mason.nvim",
  --  opts = {
  --    -- disable automatic updates
  --    automatic_installation = false,
  --  },
  --},
  --{
  --  "mason-org/mason-lspconfig.nvim",
  --  dependencies = {
  --    { "mason-org/mason.nvim", opts = {} },
  --    "neovim/nvim-lspconfig",
  --  },
  --},
    return {
    -- Just override opts, LazyVim handles lazy loading
    --{
    --  "mason-org/mason-lspconfig.nvim",
    --  opts = {
    --    ensure_installed = { "clangd", "ruff", "lua_ls", "mypy", "clang-format", "black" },
    --  },
    --},
    --{
    --  "nvim-treesitter/nvim-treesitter",
    --  opts = {
    --    ensure_installed = { "vim", "lua", "vimdoc", "cpp", "python", "json" },
    --  },
    --},
    -- Remove bare nvim-lspconfig and mason-org/mason.nvim entries — LazyVim owns those
  }
